### PR TITLE
Changes for v19

### PR DESCRIPTION
**Pull request by gade01**
- Bump xbmc.gui
- Add System.AddonIsEnabled()
- Add EnableAddon()

### CODE REVIEW

**Comment by DaVukovic** [comment]
Will have a deeper look this evening. Thanks very much for helping :+1:

**Comment by DaVukovic** [comment]
Sorry for the delay
This looks good to me. I'm not sure if the change for the LibreELEC settings is needed (IIRC you can't disable that), but it won't hurt.

If @HitcherUK agrees, then we can hit the button

Thanks much :+1:

**Comment by gade01** [comment]
> Looks good to me but we just need one more change added.
> 
> ```
> and a new button in DialogPVRInfo.xml
> - id="11" / label = 826
> ```
> 
> [https://forum.kodi.tv/showthread.php?tid=343076&pid=2846543#pid2846543](url)
> 
> Thanks.

I added that one in this commit:
https://github.com/xbmc/skin.confluence/commit/0ebecafa6755427a312cfd6f63247275f52a7a91

**Comment by gade01** [comment]
> Sorry for the delay
> This looks good to me. I'm not sure if the change for the LibreELEC settings is needed (IIRC you can't disable that), but it won't hurt.

It's probably not needed, but System.AddonIsEnabled is a more safe way for the check.

**Comment by HitcherUK** [comment]
> > Looks good to me but we just need one more change added.
> > ```
> > and a new button in DialogPVRInfo.xml
> > - id="11" / label = 826
> > ```
> > 
> > 
> > [https://forum.kodi.tv/showthread.php?tid=343076&pid=2846543#pid2846543](url)
> > Thanks.
> 
> I added that one in this commit:
> [0ebecaf](https://github.com/xbmc/skin.confluence/commit/0ebecafa6755427a312cfd6f63247275f52a7a91)

Sorry, ignore me. :)

**Comment by gade01** [comment]
Hahaha, no worries :)

**Comment by DaVukovic** [comment]
Thanks for your help :+1:

**Pull request merged**
