### PR TITLE
Fix MusicOSD.xml record button

### PR DESCRIPTION
**Pull request by gade01**
This PR will fix the PVR radio record button for master branch.
It will also fix the PVR radio recording label.

As reported here: #93

@jjd-uk as mentioned at Slack

### CODE REVIEW

**Comment by jjd-uk** [comment]
Tested on Master and working as it should.

image

However I noticed another inconsistancy with recording live tv and that is the Currently Recording label is missing when recording activated.

image

This seems to be solved by https://gist.github.com/jjd-uk/5c9d0b9f64a254e895b5f735f80f7c3e#file-musicvisualisation-xml-L128-L149

copied from https://github.com/xbmc/skin.confluence/blob/master/720p/VideoFullScreen.xml#L170-L191

Producing

image

**Comment by gade01** [comment]
Thanks for testing, and great that it's working.
I'll fix the other issue as well and include it in this PR.

**Comment by jjd-uk** [comment]
Aplogies noticed the code I posed wan't quite right, should be right this time, missed the visibility condition to hide Now Playing label and and the record image needed adjustment for viz window.

https://gist.github.com/jjd-uk/6b92c2f58ed286aeeb41200744ea8559#file-musicvisualisation-xml-L102-L138

**Comment by gade01** [comment]
Should be fixed now.
Does it work correctly?

**Comment by jjd-uk** [comment]
With last code I get

image

So matches live tv

**Comment by gade01** [comment]
Looks perfect, thanks :)

**Pull request merged**
