### PR TITLE
[UPDATE] Confluence skin changes

### PR DESCRIPTION
**Pull request by Hitcher**
All Nexus skin changes completed.

- Bump skin version and update changelog
- Add movie title format option
- Bump xbmc.gui for Nexus
- Add Nexus game changes
- Add show password button to keyboard
- Add Player.Process(videoscantype) infolabel
- Add Cuts, Scene Markers, and Editlist
- Add missing aspect ratios
- Add 'infill' attribute to border textures
- Add HDR flagging
- Delete DialogFavourites.xml
- Fix home episode thumbs not using spoiler settings
- Add default start item selection

### CODE REVIEW

**Comment by MikeSiLVO** [comment]
I am new to this so please forgive me if I misunderstand something or make a mistake. 

I think it is amazing that you took the time to update Confluence and a lot of folks will be over the moon that they have their favorite skin back as an option so thanks very much!

Only noticed the following in the PR:

Possibly missing an `S` here [ortitle_1st, ortitle_2nd, & ortitle_only](https://github.com/xbmc/skin.confluence/pull/229/files#diff-e31ed11439c6ef208b786a1f9307a75c0d2241b787514fff1f1fd23bc83c3033R604) and matching [Selectbool](https://github.com/xbmc/skin.confluence/pull/229/files#diff-6abee6da98da077f52f208d397b3888ba0888cfb84050c93227c490b7f05d689R293)? 
`Home.xml` unmatched parenthesis on lines 882, 883, & 1377.
`DialogKeyboard.xml` new button 310 has multiple font tags at lines 396 and 407

Some other issues I noticed using KodiDevkit for Sublime Text but it looks like they were in the skin already also I likely need to update the package for false positives so would be nice to get confirmation on some of them:

- `Defaults.xml` line 144 undefined font `<font>font20</font>`
- `SettingsScreenCalibration.xml` line 138 undefined font `<font>font25</font>`
- `Includes.xml` line 43 unused variable `<variable name="MusicRating">`
- DialogColorpicker.xml line 44 untranslated label `<label>Colour</label>`
- DialogButtonMenu.xml, DialogPVRGuideSearch.xml, DialogPVRChannelManager.xml, and MyPVRChannels.xml should all the `<pulseonselect>no</pulseonselect>` be changed to false? Probably doesn't matter other than KodiDevKit complaining.
- DialogSettings.xml line 73  `<reverse>yes</reverse>` not sure about this one since I cannot find a reference to reverse for spincontrolex or anywhere actually...
- DialogPVRGuideControls.xml multiple tags for align on lines 25 & 28, 91 & 94, 103 & 106, 151 & 154
- `DialogPVRRadioRDSInfo.xml` invalid label tag for spincontrol line 898 `<label/>`
- `DialogSlider.xml` invalid tag for slider `<aligny>center</aligny>` `<texturefocus/>` `<texturenofocus/>` 
- `IncludesDialogSelect.xml` multiple tags for orientation on lines 386 & 388
- `ViewsMusicLibrary.xml` line 268 diffuse? 
- `ViewsVideoLibrary.xml` lines 372 & 400 same as above
- `ViewsVideoLibrary.xml` lines 1396, 1408, & 1541 invalid attribute for bordertexture `background="true"` ?


I see new IP button 999 in DialogKeyboard to make room for 310 but am wondering if 310 can be moved to the other side instead? Could definitely not be noticing a possible issue with alternate languages here so this is just a general question :)

I also noticed no difference with removing the infill=false in some places but I did not test everywhere and perhaps I do not really understand the purpose of it besides my own experience with some images I use?

One last thing, removing what looks like is supposed to be a reflection ❓  in DialogVideoInfo.xml doesn't change anything that I noticed but it does remove some errors in the checker.

```
					<control type="image">
						<left>0</left>
						<top>250</top>
						<width>380</width>
						<height>250</height>
						<aspectratio aligny="top">keep</aspectratio>
						<bordertexture infill="false" border="5" flipy="true" diffuse="diffuse_mirror2.png">button-nofocus.png</bordertexture>
						<bordersize>4</bordersize>
						<texture background="true" flipy="true" diffuse="diffuse_mirror2.png">$INFO[ListItem.Icon]</texture>
					</control>
```

Sorry for the wall of text but wanted to be thorough.

Thanks 😃

**Comment by Hitcher** [comment]
> I am new to this so please forgive me if I misunderstand something or make a mistake.

Always good to have another pair of eyes look over any code.

> Possibly missing an `S` here [ortitle_1st, ortitle_2nd, & ortitle_only](https://github.com/xbmc/skin.confluence/pull/229/files#diff-e31ed11439c6ef208b786a1f9307a75c0d2241b787514fff1f1fd23bc83c3033R604) and matching [Selectbool](https://github.com/xbmc/skin.confluence/pull/229/files#diff-6abee6da98da077f52f208d397b3888ba0888cfb84050c93227c490b7f05d689R293)?

Most of that code is from another PR, and I did initially think it was a typo as well, but I think it stands for **or**iginal**title**. Having said that I think it might be a better idea to rename it to avoid any confusion in the future.

> `Home.xml` unmatched parenthesis on lines 882, 883, & 1377.

Missed that, thanks.

> `DialogKeyboard.xml` new button 310 has multiple font tags at lines 396 and 407

Fixed, thanks.

> * `DialogSettings.xml` line 73  `<reverse>yes</reverse>` not sure about this one since I cannot find a reference to reverse for spincontrolex or anywhere actually...

This changes the direction of the cycling actions for the left and right parts of the control but it's odd that it's not mentioned in the wiki.

> * `DialogPVRRadioRDSInfo.xml` invalid label tag for spincontrol line 898 `<label/>`

I can't test this but I assume they don't want a label to be visible so I've changed it to use no font instead.

> * `ViewsMusicLibrary.xml` line 268 diffuse?
> * `ViewsVideoLibrary.xml` lines 372 & 400 same as above

Reflection of image.

> I see new IP button 999 in DialogKeyboard to make room for 310 but am wondering if 310 can be moved to the other side instead? Could definitely not be noticing a possible issue with alternate languages here so this is just a general question :)

I wanted to keep all the 'control buttons' on the same side of the keyboard.

> I also noticed no difference with removing the infill=false in some places but I did not test everywhere and perhaps I do not really understand the purpose of it besides my own experience with some images I use?

It's used when the centre area of the border image doesn't need to be drawn because the icon will cover it.

> One last thing, removing what looks like is supposed to be a reflection ❓ in DialogVideoInfo.xml doesn't change anything that I noticed but it does remove some errors in the checker.

It's only used for reflecting episode thumbs.

All the other issues have been taken care of.

> Sorry for the wall of text but wanted to be thorough.

No need to apologise, it's appreciated.

**Comment by Hitcher** [comment]
Updated the wiki to include the `<reverse></reverse>` tags for the `spincontrolex` description.

**Comment by Hitcher** [comment]
> Thank you for this @Hitcher , Confluence remains my go to skin choice and I appreciate you keeping it a viable option

You're welcome.

I'm hoping to get it Omega ready as well and then it should be easier to keep it up-to-date with any future skin changes.

**Comment by bossanova808** [comment]
> I'm hoping to get it Omega ready as well and then it should be easier to keep it up-to-date with any future skin changes.

You are an absolute legend.  Very much appreciated!!  I reckon there's quite a few folks for whom it remains the go-to.

**Comment by jjd-uk** [comment]
I won't have time to review until the weekend, but there looks to be enough eyes on this already if you want to push before then.

> I reckon there's quite a few folks for whom it remains the go-to.

Still looks to be fairly popular

https://mirrors.kodi.tv/stats?downloadstats&filter=addons/nexus/skin

**Pull request merged**
