### PR TITLE
Omega changes

### PR DESCRIPTION
**Pull request by Hitcher**
- Add Video version support
- Convert skin from 720p to 1080p
- Update scrollbars
- Add grid overlay
- Add game agents
- Add disabled slider texture

### CODE REVIEW

**Comment by wuweifly** [comment]
Please fix missing label issue.
A lot addons has no label for each row in Big List View.

**Comment by Frencman** [comment]
Just updated from 21 beta to 21 stable and it disabled the Confluence skin that was running so nicely on install.  Tried to add skin via zip file but it would not go through.  You helped me before - any ideas on this instance?
Thanx - Paul

**Comment by Hitcher** [comment]
> Tried to add skin via zip file but it would not go through

You'll need to install the Omega version from [here](https://github.com/Hitcher/skin.confluence) for now.

**Comment by bossanova808** [comment]
I've just started testing with Omega released version.  I think there's a small bug with the original title/localised title logic.

I'd expect Localised Title (Original Title) to result in

My Neighbour Totoro (-> Japanese Symbols if fonts supports)
The Crime Is Min (-> Mon Crime)

But instead I am seeing the inverse:

image

So that seems wrong to me?  If I change the settings to Original Title (Localised Title), I then see what I expect to see with the other settings.

**Comment by bossanova808** [comment]
Another (minor) thing noticed - in Thumbnails view, it now shows an empty extra row at the bottom of all the rows, that was not there previously:

image

**Comment by delight** [comment]
@bossanova808 how did you get Confluence into Omega? Or rather will it pop up in the "More..." list of the offered Skins from the default Kodi Repository over time? Sorry, the question might be a little misplaced ... would love to have Confluence in Omega.

**Comment by bossanova808** [comment]
I'm using my own fork with these changes from @Hitcher integrated.  You can either get a .zip from Hitcher's repo, or wait until these changes are pushed to the main Kodi repo (which I imagine won't be long given the recent Omega official release).

**Comment by Hitcher** [comment]
> I've just started testing with Omega released version. I think there's a small bug with the original title/localised title logic.

That wasn't my PR https://github.com/xbmc/skin.confluence/pull/160 but I think you're right. Will fix it.

**Comment by Hitcher** [comment]
> Another (minor) thing noticed - in Thumbnails view, it now shows an empty extra row at the bottom of all the rows, that was not there previously:

These are the sort things that crop up when you convert from 720>1080. Simple fix, thanks for reporting.

**Comment by Frencman** [comment]
> I'm using my own fork with these changes from @Hitcher integrated. You can either get a .zip from Hitcher's repo, or wait until these changes are pushed to the main Kodi repo (which I imagine won't be long given the recent Omega official release).

Downloaded from @Hitcher and it works !!!  Thanx for all your effort folks !!!

**Pull request closed without merging**
