### PR TITLE
More granual playback speed control

### PR DESCRIPTION
**Pull request by k3a**
This needs feedback or discussion. It is probably not directly merge-able.

I have changed Fast Forward / Fast Rewind to allow speeding up / slowing down the playback by 0.1x increments because I found no other way to change the playback speed other than using keyboard shortcuts or sending custom API commands.

This looks like something [more people want](https://www.google.com/search?q=kodi+change+playback+speed).

Is there no existing playback speed control or have I missed something?

I am ok to use it in my personal fork but I thought I would create this PR to discuss this and see if more people would like something like that?

### CODE REVIEW

**Comment by DaVukovic** [comment]
Hi and thanks for your contribution. 

Playback speed can be controlled via `TempoUp` or `TempoDown` as long as there's no passthrough in use. 

Those commands can be mapped to any keyobard shortcut you like or to any remote button you would like to have it. There's no need to hardcode that into a skin. Hardcoding that to a skin would mean that others who like to use passthrough on their systems will end up in non-functional buttons. 

We could probably talk about that if your conditions are based on `Player.Passthrough` which returns true if the player is using audio passthrough and if so, those buttons should have the same function as they had before. 

Currently this PR would get a :-1: from my side.

**Comment by k3a** [comment]
Thanks for the thorough explanation.

The problem is, I don't use keyboard when using Kodi.
I use a smartphone with remote control app and it doesn't support tempo, therefore I need a GUI button to set up the playback speed.

It looks like that << and >> buttons (Fast Forward / Fast Rewind) are supposed to set the playback speed. But in the stock Confluence (main branch) state, it offers only 2x and 4x options to me!
I have "Sync playback with display" enabled. I also tried to explicitly disable Passthrough but it would still offer only 2x and 4x.

That's why I made this hack, which makes it possible for me to increase speeds in 0.1 increments and displays the speed as textual value instead of a bitmap. I know it is not mergeable in the current state.

I understand that some people need pass-through and I can confirm that my hack works only if "Sync playback with display" is enabled, which results in disabling pass-through.

But in my opinion, Kodi as a player should support more granular playback speed. Most video players including Vimeo, YouTube nad NetFlix support multiple playback speeds (1.6, 1.8, etc).

I don't know what is blocking having gradual speed setting implemented in Kodi.
For example can't you dynamically enable/disable passthrough depending on the current speed setting?
Or can't you offer setting granular speeds for people having "Sync playback to display" on?

Those onclick conditions look confusing to me, are they even correct? Player.IsTempo vs Player.TempoEnabled ?

**Comment by DaVukovic** [comment]
>For example can't you dynamically enable/disable passthrough depending on the current speed setting?

No, as ppl might have different audio hardware with different capabilities (DD capable only or DD and DTS but no HD audio...and many more combinations are possible). 

> Those onclick conditions look confusing to me, are they even correct? Player.IsTempo vs Player.TempoEnabled ?

tbh, I haven't tested your code at all and did not made any thought if it's correct or not ;). After I saw that you suggest to force `TempoUp/Down` for those buttons and don't rely on passthrough setting it was pretty clear to me that we won't merge this PR (no offense). 
Hacking this kind of stuff into a local setup is fine. So please, keep your setup if it works for you. But it won't get merged in its current state. 

If you want to save hacking-time, I would suggest to start a feature request at the specific forum thread: 
https://forum.kodi.tv/forumdisplay.php?fid=125
We could discuss the circumstances where such a change might be considered. 

> But in my opinion, Kodi as a player should support more granular playback speed.

The problem here is, that you hacked a Kodi skin into a functionality where you should probably better ask for a change for the control app you are using (may it be Kore or Yatse or whatever). You are hitting forward/rewind buttons on your remote-app and these send *specific* commands to Kodi. Kodi *expects* such specific commands and you simply changed to skin to behave differently to what 

* the control app is meant to do
* every IR remote out there is meant to do
* every standard keyboard shortcut is meant to do

If we accept such a change, every user out there who is using Confluence will suffer from that. It would be WAY better if the control app offers such buttons (probably some additional buttons maybe) and you simply have to disable passthrough/enable "Sync playback to display" to make those buttons work. That would be the same behavior we currently have while using IR-remotes or keyboards where users are able to map those commands to their devices. No user will end up in non-functional buttons and we, as the maintainers, don't have to think of to many conditions a simple forward/rewind button might have ;)

Sorry...but the more I think about that, the more I get convinced to not include such a change.

**Comment by DaVukovic** [comment]
And we have to mention, that the functionality is already there. Just simply pause the player first and then hit fast forward:

<onclick condition="Player.Paused + Player.TempoEnabled">PlayerControl(TempoDown)</onclick>


Downside is, that this section will always be visible:
image

This could probably be improved. But the functionality is already there if you hit "pause" first

**Comment by k3a** [comment]
Thanks again for the great explanation!

This functionality was there, indeed! Sorry, it was my misunderstanding. I actually made this hack about a year ago and I was forced to rebase it to your master due to a local Kodi update and I didn't realize what I actually did back then. I feel bad now. :(

I have now retested it and made a minimal patch of what I really need:
- Seek bar should be hidden while tempo is enabled so I can watch sped-up video without this OSD
- It should display speeds higher than 1.5x. By default bitmap speed indication stops at 1.5 and then there is empty space until 2.0x.

I have updated my branch but I know this is probably not good for other people either.
So let's end this with realization that there are these two minor inconvenieces but they are probably not worth "fixing".
Some people may want this OSD visible during faster playback and making 1.6, 1.7, ... 2.0x indicators would probably need new bitmaps.

Let's close this PR then. And again, sorry for the misunderstanding!
Thanks for making this skin, I like this skin the most btw.

**Comment by gade01** [comment]
Hi @k3a 

I will probably soon look into doing some improvements for tempo control.
They could most likely be improved. :)

**Comment by gade01** [comment]
@k3a 
I took this PR into account when creating https://github.com/xbmc/skin.confluence/pull/117
It has support for play speeds 1.6, 1.7, 1.8, 1.9, 2.0, 2.1.
And it hides the entire OSD when tempo control is used.
Feel free to test it.

**Comment by k3a** [comment]
Thanks for that, good work! That fixes the issue so closing this PR. Yes, it may look a bit distracting that it pops up on top of Play but at least everyone will see the function is there and how to use it immediately. Additionally it can be used while something is playing. Previously it was like a hidden secret function, working only while paused and making fast forward/backward button function inconsistent between paused and playing states. Also that displays speeds > 0.5x, cool :)

**Comment by gade01** [comment]
Sounds great.
Thanks a lot for your inputs and for testing .

**Pull request closed without merging**
