### PR TITLE
Dynamic content for home screen widgets

### PR DESCRIPTION
**Pull request by gade01**
This PR will switch to dynamic content for all home screen widgets.

This has a lot of benefits:
- Faster
- Code cleanup (250+ less lines)
- Fanart is available and set
- Context menus are working
- Information windows can be opened directly from widgets

Also fixes the issue mentioned here: https://forum.kodi.tv/showthread.php?tid=356715

### CODE REVIEW

**Comment by bossanova808** [comment]
+1 for this!

**Review by DaVukovic — APPROVED** [review]
Tested and it works great. Thanks much :+1:

**Comment by bossanova808** [comment]
I have one question on this - anyway to have it show only unwatched items as an alternative?  I have long used skin widgets and a hacked Confluence for this - I am wondering if, on top of this approach, there is now an easier way...

**Comment by gade01** [comment]
@bossanova808  It's no problem showing only unwatched items using dynamic content.

But Confluence's users are not used to this. So I'm not sure.

Maybe it should be added as a skin setting?

@DaVukovic @HitcherUK  
Any thoughts on this?

**Comment by bossanova808** [comment]
It is (was) an oft-requested feature in the forums (and lots of other skins do this by default, cause it's pretty logical),

The main blocker, in the past, was spiff, IIRC - he had a thing about it being recentl added, not recently added-unwatched.

But I would hazard a guess most folks would prefer to be 'new stuff' in the more general sense...and things once has watched...is not really new anymore...

**Comment by gade01** [comment]
That's logical. I do the same in Rapier.

But for Confluence, I think I would do a skin setting for this.
Default is show all items. Enabling the skin setting will show only unwatched.

**Comment by HitcherUK** [comment]
Sorry I've not replied until now but I've had no internet for 4 days.
Anyway this looks good to me and I'd also change it to hide watched recently added episodes as well. The only reason I didn't change before now was because we were still using the old core items. This is now the default way in Estuary as well.

**Review by HitcherUK — COMMENTED** [review]
Good to go.

**Comment by gade01** [comment]
@HitcherUK 
So you think widgets should hide watched by default?

**Comment by HitcherUK** [comment]
> So you think widgets should hide watched by default?
> 
> As far as I remember, Estuary doesn't hide watched items in widgets?

Yes I do and I just tested Estuary to be sure and it also hides watched movies from the recently added list. You can easily test using the context menu right on the home screen.

**Comment by gade01** [comment]
OK, that's much easier.
Thanks.

I'll create a separate PR for that once this is merged.

**Comment by HitcherUK** [comment]
Done, thanks.

**Pull request merged**
