### PR TITLE
[master] Add OSD dialog to control tempo

### PR DESCRIPTION
**Pull request by gade01**
- This adds a dialog to control tempo in fullscreen video window for master branch.
- This also fixes the SeekLabel and animations for tempo control.
- DialogSeekBar.xml will be hidden after `System.IdleTime(3)` if `Player.IsTempo`.
- DialogSeekBar.xml will now use a label to indicate PlaySpeed instead of images. This will add support for PlaySpeed 1.6, 1.7, 1.8, 1.9, 2.0, 2.1.

@jjd-uk @DaVukovic @HitcherUK 
As discussed at Slack

screenshot00001

screenshot00002

### CODE REVIEW

**Comment by jjd-uk** [comment]
I've now been able to test this.

Personally I don't like the dialog overlapping the video item details, what about moving it up like

image

I also don't with the seebar details being active while the tempo is active, so I also got rid of that as shown in the screenshot.

My code for that is https://gist.github.com/jjd-uk/d36df60bef4a232dded39a2df30bc56f

**Comment by jjd-uk** [comment]
Just noticed, for consistancy the grouplist id=500 may also have to be moved up. That would look like

image

**Comment by gade01** [comment]
@jjd-uk 
Sorry, I don't agree on this,
If the dialog is moved, I think it's floating by itself out of place with the rest of the OSD.

By design, it should be placed directly on top of the OSD buttons. That makes the arrow point to the button.
This is the case with the 3D dialog (like you found out), and that was the case with the subtitle dialog (now replaced with DialogSettings.xml).
With the new tempo dialog, I copied the vertical placement directly from the old dialogs.

> I also don't think we should have the seebar details being active while the tempo is active

The seekbar displays the tempo and how fast/slow it is. Removing that will remove that info and that would be a shame.
What we can do, is remove the end time and movie info when tempo control is used.
That makes it look very clean:

screenshot00000

The only thing is that I can't figure out why the progressbar slider isn't respecting the visible conditions.

@HitcherUK Any thoughts on this whole deal?

**Comment by jjd-uk** [comment]
I also had another reason for removing the seekbar info and that was because it's wrong. When play speed is less than 1 e.g. 0.8 it says rewind, this is wrong as you're still watching in a forward direction just at a slower speed. When speed is greater than 1 is says fast forward which again is wrong. In addition as the user pointed out there's no images for speeds 1.6, 1.7, 1.8, 1
9, 2.0 and 2.1.

**Comment by gade01** [comment]
Ahaaaaa, I see.

That could be fixed.
I'll look at that.

**Comment by gade01** [comment]
Ahaaaaa, I see.

That could be fixed.
I'll look at that.

**Comment by jjd-uk** [comment]
Regarding positioning of the dialog. When testing I didn't like it auto-appearing when going over the play/pause button creating that overlapping. However as discussed previously we don't really have any good way with Confluence to activate the dialog without doing that, hence the experiment of moving it up, but I agree the floating nature of it so the arrow tip no longer points directly onto button is not ideal either.

**Comment by jjd-uk** [comment]
If we need to keep to auto-appearing and position then I think I'd prefer to keep it as now with the overlap, rather than what you've done in your screenshot in the reply to my comment. Seems like any solution maybe a compromise, so as you have is maybe best compromise, unless anyone else has any good ideas.

**Comment by gade01** [comment]
Yeah, I agree on that.
Looking at the newest screenshot again, I don't think I really like the hiding of movie info etc.
It looks like a hack.

Let's see if there are some other inputs on this.

Did you test the fixed SeekLabel?

**Comment by HitcherUK** [comment]
The seekbar needs to be hidden once the user has set the playback speed because they'll then want to watch the video without any dialogs visible. Remember this is for watching at a slower or faster speed not for seeking to a certain position.

**Comment by gade01** [comment]
We can just hide the seekbar after 2 seconds if tempo control is used.

Something like this:

```<?xml version="1.0" encoding="UTF-8"?>
<window>
	<defaultcontrol>1</defaultcontrol>
	<visible>Player.Seeking | Player.DisplayAfterSeek | Player.Paused | Player.Forwarding | Player.Rewinding | Player.ShowTime | Player.IsTempo</visible>
	<visible>!Player.HasGame</visible>
	<visible>!Player.FrameAdvance</visible>
	<animation effect="fade" start="0" end="100" time="150">WindowOpen</animation>
	<animation effect="fade" start="100" end="0" time="150">WindowClose</animation>
	<depth>DepthOSD</depth>
	<controls>
		<control type="group">
			<visible>Window.IsVisible(FullscreenVideo) + ![Player.HasGame | VideoPlayer.HasEpg] + ![Player.IsTempo + System.IdleTime(2)]</visible>
			<left>850r</left>
			<top>-6</top>
			<include>VisibleFadeEffect</include>
			<control type="image">
				<left>0</left>
				<top>0</top>
				<width>150</width>
				<height>70</height>
				<colordiffuse>EEFFFFFF</colordiffuse>
				<texture border="12">OverlayDialogBackground.png</texture>
			</control>
			<control type="label" id="1">
				<description>End time label</description>
				<left>20</left>
				<top>10</top>
				<width>110</width>
				<height>20</height>
				<align>center</align>
				<aligny>center</aligny>
				<font>font12_title</font>
				<textcolor>blue</textcolor>
				<scroll>true</scroll>
				<label>$LOCALIZE[31049]</label>
			</control>
			<control type="label" id="1">
				<description>End time from infolabel</description>
				<left>20</left>
				<top>30</top>
				<width>110</width>
				<height>20</height>
				<align>center</align>
				<aligny>center</aligny>
				<font>font13_title</font>
				<textcolor>grey2</textcolor>
				<label>$INFO[Player.FinishTime]</label>
			</control>
		</control>
		<control type="group">
			<visible>player.chaptercount + Window.IsVisible(FullScreenVideo) + !Player.IsTempo</visible>
			<left>705r</left>
			<top>-6</top>
			<include>VisibleFadeEffect</include>
			<control type="image">
				<left>0</left>
				<top>0</top>
				<width>150</width>
				<height>70</height>
				<colordiffuse>EEFFFFFF</colordiffuse>
				<texture border="12">OverlayDialogBackground.png</texture>
			</control>
			<control type="label" id="1">
				<description>Chapter Pos No</description>
				<left>20</left>
				<top>10</top>
				<width>110</width>
				<height>20</height>
				<align>center</align>
				<aligny>center</aligny>
				<font>font12_title</font>
				<textcolor>blue</textcolor>
				<label>$LOCALIZE[21396]</label>
				<visible>player.chaptercount</visible>
			</control>
			<control type="label" id="1">
				<description>Chapter Pos No</description>
				<left>20</left>
				<top>30</top>
				<width>110</width>
				<height>20</height>
				<align>center</align>
				<aligny>center</aligny>
				<font>font13_title</font>
				<textcolor>grey2</textcolor>
				<label>$INFO[player.chapter]$INFO[player.chaptercount, / ]</label>
				<visible>player.chaptercount</visible>
			</control>
		</control>
		<control type="group">
			<visible>![Player.IsTempo + System.IdleTime(2)]</visible>
			<left>560r</left>
			<top>-6</top>
			<control type="image">
				<left>0</left>
				<top>0</top>
				<width>370</width>
				<height>70</height>
				<colordiffuse>EEFFFFFF</colordiffuse>
				<texture border="12">OverlayDialogBackground.png</texture>
			</control>
			<control type="group">
				<left>260</left>
				<top>10</top>
				<control type="image">
					<left>10</left>
					<top>0</top>
					<width>80</width>
					<height>50</height>
					<texture>OSDSeekFrame.png</texture>
				</control>
				<control type="image">
					<left>0</left>
					<top>3</top>
					<width>20</width>
					<height>44</height>
					<texture>OSDSeekRewind.png</texture>
					<visible>Player.Rewinding | [Player.IsTempo + String.StartsWith(Player.PlaySpeed,0.)]</visible>
				</control>
				<control type="image">
					<left>80</left>
					<top>3</top>
					<width>20</width>
					<height>44</height>
					<texture>OSDSeekForward.png</texture>
					<visible>Player.Forwarding | [Player.IsTempo + String.StartsWith(Player.PlaySpeed,1.)]</visible>
				</control>
				<control type="image">
					<left>31</left>
					<top>4</top>
					<width>40</width>
					<height>40</height>
					<texture>OSDPause.png</texture>
					<visible>Player.Paused</visible>
				</control>
				<control type="image">
					<left>31</left>
					<top>4</top>
					<width>40</width>
					<height>40</height>
					<texture>OSDPlay.png</texture>
					<visible>Player.Playing + !Player.IsTempo</visible>
				</control>
				<control type="image">
					<left>28</left>
					<top>4</top>
					<width>40</width>
					<height>40</height>
					<texture>OSD2x.png</texture>
					<visible>Player.Rewinding2x</visible>
				</control>
				<control type="image">
					<left>28</left>
					<top>4</top>
					<width>40</width>
					<height>40</height>
					<texture>OSD0.9x.png</texture>
					<visible>String.IsEqual(Player.PlaySpeed,0.90)</visible>
				</control>
				<control type="image">
					<left>25</left>
					<top>4</top>
					<width>40</width>
					<height>40</height>
					<texture>OSD4x.png</texture>
					<visible>Player.Rewinding4x</visible>
				</control>
				<control type="image">
					<left>25</left>
					<top>4</top>
					<width>40</width>
					<height>40</height>
					<texture>OSD0.8x.png</texture>
					<visible>String.IsEqual(Player.PlaySpeed,0.80)</visible>
				</control>
				<control type="image">
					<left>22</left>
					<top>4</top>
					<width>40</width>
					<height>40</height>
					<texture>OSD8x.png</texture>
					<visible>Player.Rewinding8x</visible>
				</control>
				<control type="image">
					<left>19</left>
					<top>4</top>
					<width>40</width>
					<height>40</height>
					<texture>OSD16x.png</texture>
					<visible>Player.Rewinding16x</visible>
				</control>
				<control type="image">
					<left>17</left>
					<top>4</top>
					<width>40</width>
					<height>40</height>
					<texture>OSD32x.png</texture>
					<visible>Player.Rewinding32x</visible>
				</control>
				<control type="image">
					<left>34</left>
					<top>4</top>
					<width>40</width>
					<height>40</height>
					<texture>OSD2x.png</texture>
					<visible>Player.Forwarding2x</visible>
				</control>
				<control type="image">
					<left>34</left>
					<top>4</top>
					<width>40</width>
					<height>40</height>
					<texture>OSD1.1x.png</texture>
					<visible>String.IsEqual(Player.PlaySpeed,1.10)</visible>
				</control>
				<control type="image">
					<left>37</left>
					<top>4</top>
					<width>40</width>
					<height>40</height>
					<texture>OSD4x.png</texture>
					<visible>Player.Forwarding4x</visible>
				</control>
				<control type="image">
					<left>37</left>
					<top>4</top>
					<width>40</width>
					<height>40</height>
					<texture>OSD1.2x.png</texture>
					<visible>String.IsEqual(Player.PlaySpeed,1.20)</visible>
				</control>
				<control type="image">
					<left>40</left>
					<top>4</top>
					<width>40</width>
					<height>40</height>
					<texture>OSD8x.png</texture>
					<visible>Player.Forwarding8x</visible>
				</control>
				<control type="image">
					<left>40</left>
					<top>4</top>
					<width>40</width>
					<height>40</height>
					<texture>OSD1.3x.png</texture>
					<visible>String.IsEqual(Player.PlaySpeed,1.30)</visible>
				</control>
				<control type="image">
					<left>43</left>
					<top>4</top>
					<width>40</width>
					<height>40</height>
					<texture>OSD16x.png</texture>
					<visible>Player.Forwarding16x</visible>
				</control>
				<control type="image">
					<left>43</left>
					<top>4</top>
					<width>40</width>
					<height>40</height>
					<texture>OSD1.4x.png</texture>
					<visible>String.IsEqual(Player.PlaySpeed,1.40)</visible>
				</control>
				<control type="image">
					<left>45</left>
					<top>4</top>
					<width>40</width>
					<height>40</height>
					<texture>OSD32x.png</texture>
					<visible>Player.Forwarding32x</visible>
				</control>
				<control type="image">
					<left>45</left>
					<top>4</top>
					<width>40</width>
					<height>40</height>
					<texture>OSD1.5x.png</texture>
					<visible>String.IsEqual(Player.PlaySpeed,1.50)</visible>
				</control>
			</control>
			<control type="label">
				<description>Seekbar Label</description>
				<left>20</left>
				<top>7</top>
				<width>240</width>
				<height>20</height>
				<align>left</align>
				<aligny>center</aligny>
				<font>font10_title</font>
				<textcolor>blue</textcolor>
				<label>$VAR[SeekLabel]</label>
			</control>
			<control type="group">
				<visible>[VideoPlayer.Content(LiveTV) + VideoPlayer.HasEpg]</visible>
				<control type="label">
					<description>Elapsed Time Label</description>
					<left>20</left>
					<top>23</top>
					<width>240</width>
					<height>20</height>
					<font>font13_title</font>
					<textcolor>white</textcolor>
					<align>left</align>
					<aligny>center</aligny>
					<label>$INFO[PVR.EpgEventElapsedTime] - $INFO[PVR.EpgEventDuration]</label>
					<visible>!Player.Seeking</visible>
				</control>
				<control type="label">
					<description>Seek Time Label</description>
					<left>20</left>
					<top>23</top>
					<width>240</width>
					<height>20</height>
					<font>font13_title</font>
					<textcolor>white</textcolor>
					<align>left</align>
					<aligny>center</aligny>
					<label>$INFO[PVR.EpgEventSeekTime] - $INFO[PVR.EpgEventDuration]</label>
					<visible>Player.Seeking</visible>
				</control>
				<control type="progress">
					<description>ProgressbarTimeshift</description>
					<left>20</left>
					<top>45</top>
					<width>240</width>
					<height>15</height>
					<info>PVR.TimeshiftProgressBufferEnd </info>
					<midtexture border="6,0,6,0">OSDProgressMidLight.png</midtexture>
					<visible>PVR.IsTimeShift</visible>
				</control>
				<control type="progress" id="23">
					<description>Progressbar</description>
					<left>20</left>
					<top>45</top>
					<width>240</width>
					<height>15</height>
					<info>PVR.EpgEventProgress</info>
					<visible>true</visible>
				</control>
				<control type="slider" id="403">
					<description>Seek Slider</description>
					<left>20</left>
					<top>42</top>
					<width>240</width>
					<height>12</height>
					<texturesliderbar>seekslider.png</texturesliderbar>
					<textureslidernib>osd_slider_nib.png</textureslidernib>
					<textureslidernibfocus>osd_slider_nib.png</textureslidernibfocus>
					<visible>Player.Seeking</visible>
				</control>
			</control>
			<control type="group">
				<visible>![VideoPlayer.Content(LiveTV) + VideoPlayer.HasEpg]</visible>
				<control type="label">
					<description>Elapsed Time Label</description>
					<left>20</left>
					<top>23</top>
					<width>240</width>
					<height>20</height>
					<font>font13_title</font>
					<textcolor>white</textcolor>
					<align>left</align>
					<aligny>center</aligny>
					<label>$INFO[Player.Time] - $INFO[Player.Duration]</label>
					<visible>!Player.Seeking</visible>
				</control>
				<control type="label">
					<description>Seek Time Label</description>
					<left>20</left>
					<top>23</top>
					<width>240</width>
					<height>20</height>
					<font>font13_title</font>
					<textcolor>white</textcolor>
					<align>left</align>
					<aligny>center</aligny>
					<label>$INFO[Player.SeekTime] - $INFO[Player.Duration]</label>
					<visible>Player.Seeking</visible>
				</control>
				<control type="progress">
					<description>ProgressbarCache</description>
					<left>20</left>
					<top>45</top>
					<width>240</width>
					<height>15</height>
					<info>Player.ProgressCache</info>
					<midtexture border="6,0,6,0">OSDProgressMidLight.png</midtexture>
					<visible>true</visible>
				</control>
				<control type="progress" id="23">
					<description>Progressbar</description>
					<left>20</left>
					<top>45</top>
					<width>240</width>
					<height>15</height>
					<info>Player.Progress</info>
					<visible>true</visible>
				</control>
				<control type="slider" id="401">
					<description>Seek Slider</description>
					<left>20</left>
					<top>42</top>
					<width>240</width>
					<height>12</height>
					<texturesliderbar>seekslider.png</texturesliderbar>
					<textureslidernib>osd_slider_nib.png</textureslidernib>
					<textureslidernibfocus>osd_slider_nib.png</textureslidernibfocus>
					<visible>Player.Seeking</visible>
				</control>
			</control>
		</control>
	</controls>
</window>
```

**Comment by gade01** [comment]
Or maybe we should hide the entire OSD after 2 seconds (`System.IdleTime(2)`).

**Comment by gade01** [comment]
I pushed a commit that will hide the entire OSD after 3 seconds.

**Comment by gade01** [comment]
Updated PR with support for PlaySpeed 1.6, 1.7, 1.8, 1.9, 2.0, 2.1.

DialogSeekBar.xml will now use a clean image and a label to indicate PlaySpeed.
All tempo control will display "Playing" and use OSDSeekForward.png image.

@jjd-uk @HitcherUK Feel free to test this. :)

**Comment by k3a** [comment]
I like it a lot! Initially it seemed a bit strange that it would overlap the movie title but I like that it makes the speed control function obvious and easily accessible. Normally I already know what video is being played and if I am not sure, I can defocus the Play button to see it fully.

Maybe it could be made to hide after couple of seconds of inactivity on the speed control, re-appearing after focusing Play/Pause button again? But I would be happy with the way it is personally.

**Comment by jjd-uk** [comment]
There is odd behaviour when tempo is active.

See https://youtu.be/88e5zYDceOU

I increase Play Speed to 1.5 then wait for OSD to time out, 

I am using a leyboard for this testing so once OSD has time out I keyboard M key (action **OSD** https://github.com/xbmc/xbmc/blob/master/system/keymaps/keyboard.xml#L363)  this is when the oddity happens. At 32s mark in video I press M the lower OSD briefly flashes on and then disappears, to get the OSD to appear I must press M a 2nd time which what happens at the 35s mark when OSD appears.

**Comment by gade01** [comment]
@jjd-uk 
Thanks for the detailed description.
I was able to recreate it and fixed the issue.
It was some wrong animations and visible conditions.

Please test and let me know if the issue is fixed.

**Comment by gade01** [comment]
@k3a Thanks a lot for testing it and for your inputs.

> Maybe it could be made to hide after couple of seconds of inactivity on the speed control, re-appearing after focusing Play/Pause button again? But I would be happy with the way it is personally.

It should already hide all OSD after 3 seconds of inactivity.
Did you try latest commits?

**Comment by jjd-uk** [comment]
@gade01 Opening the OSD problem with keyboard M key is fixed, but there is now a new problem that OSD can't now be closed using the M key as M key should be able to toggle OSD on and off. This happens even when Play Speed is left untouched at x1.

**Comment by gade01** [comment]
@HitcherUK @jjd-uk 
Updated PR:
- Player.IsTempo will only hide DialogSeekBar.xml
- This fixes (fingers crossed) all issues.

**Comment by jjd-uk** [comment]
@gade01 Re-tested and all issues are fixed. Looks good to merge to me.

**Comment by gade01** [comment]
@jjd-uk Sounds great, thanks. 
Thanks a lot  for testing and for the feedback.

**Comment by bossanova808** [comment]
I gave this a try out.  To be honest, it's not all that relevant to me as I mostly don't use sync playback to display (not used/recommended with Coreelec)...so Kodi doesn't allow temp changes.  But, I do occasionally use Kodi Windows, where I do use sync to display, so was interested.

I found the play-speed of 0 when paused a bit odd - my initial instinct was to pause the video, then adjust the playspeed, then re-start playback - this results in a lot less jank during the actual adjustment change of play speed.  Might it not be better to change the label of the dialogue to 'paused', when paused, and rather than putting zero in, leave the current play speed value in there?

Also - I agree that it's kind of a visual compromise as it stands.  Might it at least not be better if the play speed dialogue were hidden by default, and only accessible by using `onup` when on the play button (so up arrow on remote/keyboard)?  

This is, after all, a power user feature, on a no-longer-default skin - that way it would be accessible to those that want it, but not such an obscuring thing in the more general circumstance?

Other than those comments, it all seems to be working as I'd expect.

**Comment by gade01** [comment]
Superseded by https://github.com/xbmc/skin.confluence/pull/200

**Pull request closed without merging**
