### PR TITLE
[Master] Move search & add home screen button settings

### PR DESCRIPTION
**Pull request by jjd-uk**
Placement of the Search button looks out of place.

image

This has been raised a few times on the forum see https://forum.kodi.tv/showthread.php?tid=363918 and https://forum.kodi.tv/showthread.php?tid=355958&pid=2966342#pid2966342

Search would seem to be more appropriate to have along the Power/Favourites buttons

image

As we have settings to Hide/Show for everything else displayed on Home, I've also added settings to allow hiding of the new Search button and the existing Favourites button

image

image

### CODE REVIEW

**Comment by jjd-uk** [comment]
@gade01 & @HitcherUK

**Comment by gade01** [comment]
Great idea and it looks really good.
I have a few comments.

**Comment by gade01** [comment]
IncludesHomeRecentlyAdded.xml:

`<ondown>608</ondown>`:
https://github.com/xbmc/skin.confluence/blob/master/720p/IncludesHomeRecentlyAdded.xml#L43
https://github.com/xbmc/skin.confluence/blob/master/720p/IncludesHomeRecentlyAdded.xml#L197
https://github.com/xbmc/skin.confluence/blob/master/720p/IncludesHomeRecentlyAdded.xml#L377

Should be replaced with: 

`<ondown condition="Control.IsVisible(600)">600</ondown>`
`<ondown condition="!Control.IsVisible(600)">9000</ondown>`

**Comment by gade01** [comment]
If you show the Search button but hide the Favourites button there is an unwanted gap between the buttons.

This can be solved either by turning group control id=10 into a grouplist or by adding a slide animation to the search button and image if the favourites button is hidden.

**Review by gade01 — COMMENTED** [review]
IncludesHomeRecentlyAdded.xml:

`<ondown>608</ondown>`:
https://github.com/xbmc/skin.confluence/blob/master/720p/IncludesHomeRecentlyAdded.xml#L43
https://github.com/xbmc/skin.confluence/blob/master/720p/IncludesHomeRecentlyAdded.xml#L197
https://github.com/xbmc/skin.confluence/blob/master/720p/IncludesHomeRecentlyAdded.xml#L377

Should be replaced with: 

`<ondown condition="Control.IsVisible(600)">600</ondown>`
`<ondown condition="!Control.IsVisible(600)">9000</ondown>`

If you show the Search button but hide the Favourites button there is an unwanted gap between the buttons.

This can be solved either by turning group control id=10 into a grouplist or by adding a slide animation to the search button and image if the favourites button is hidden.

**Comment by jjd-uk** [comment]
@gade01 comments addressed

**Comment by gade01** [comment]
@jjd-uk 
This is great.
All is looking good.

To completely go into details, there's probably no need for this group:
https://github.com/xbmc/skin.confluence/blob/a04bb7879a49ae5a07bddead8a32eafbe0665d37/720p/Home.xml#L1189-L1215

**Comment by jjd-uk** [comment]
@gade01 yep I realise the group is not necessay for the 2 power controls, I simply did that way to keep consistancy of structure with the other 2 buttons. I've no problem removing it if you want.

**Pull request merged**
