### PR TITLE
Playerprocessinfo improvements

### PR DESCRIPTION
**Pull request by frodo19**
I made some improvement in confluence skin, updated some button in video osd, for better resolution.

Added to auto hide video osd , in the skin settings. 

Added playerprocessinfo button to the video osd.

Added the button OSDHelpText for video osdbuttons.

Added and some values, and  reorganized the playerprocessinfo, to fit for kodi, and for coreelec.

1conf

2conf

3conf

### CODE REVIEW

**Comment by Hitcher** [comment]
Everything looks good to to me, @jjd-uk any thoughts?

**Comment by bossanova808** [comment]
Minor quibble but Information**s** -> Information, in the translations (i.e. 'CPU Information' is correct English).

**Comment by jjd-uk** [comment]
There's several problems with this in my view.

It looks to be based on a Master version before https://github.com/xbmc/skin.confluence/pull/287 as the fixes there for the missing Teletext button are not included here.

Access to **playerprocess** is already included in the Options menu

image

Adding a button to **playerprocess** on main OSD leaves no room for the **3D** button if **Menu** button also exists, this is why playerprocess was added to Options menu in https://github.com/xbmc/skin.confluence/pull/283

image

If adding a new texture then the raw texture should be included, so if adding a texture for a new OSD button then the raw button png file must be included to https://github.com/xbmc/skin.confluence/tree/master/media

What is included here is the compiled **texture.xbt** which is wrong for upstream.

There is also a non-English translation file included here, https://github.com/frodo19/skin.confluence/blob/master/language/resource.language.hu_hu/strings.po as translations are handled by Weblate I am not sure this is correct. Might need to check with @gade01

**Comment by jjd-uk** [comment]
I'm still looking at the changes to the **DialogPlayerProcessInfo.xml** itself, not convinced it's the best of layouts, but I'll withhold a final verdict until I've had chance to look in more detail.

**Comment by frodo19** [comment]
I close this now, will add another pr.

**Pull request closed without merging**
