### PR TITLE
Fix MusicOSD.xml record button

### PR DESCRIPTION
**Pull request by gade01**
This PR will fix the PVR radio record button for Leia branch.
It will also fix the PVR radio recording label.

As reported here: #93
@Max11223344 please check if this fixes your issue.

@jjd-uk as mentioned at Slack

### CODE REVIEW

**Comment by Max11223344** [comment]
As i am new to this patching: I I added the lines with the + in front. The first time i selected a station and started recording nothing changed. The button remained white - no additional red on-screen button. Leaving the station screen going back to all channels there was the red button in the channel list.. Going back to the selected station: all white. Playing with the keyboard (Esc, home, back and so on i suddenly had the red recording button and the addional red button on screen. Stopping the recording the button turned white. Since then i didn't succeed in making it red again via recording. Maybe i made a mistake (?). Can i have the complete MusicOSD.xml?
screenshot004
screenshot001

**Comment by gade01** [comment]
https://github.com/xbmc/skin.confluence/blob/737bdda244dad8ecb57eab238842aa02b6d5990f/720p/MusicOSD.xml

**Comment by Max11223344** [comment]
I think the link/file is wrong. The size is about 200k - the old MusicOSD.xml was only 13k. And: it doesn't work. Selecting a channel the screen changes to the channel, but there are no more any buttons at all.

**Comment by Max11223344** [comment]
... and the mouse is 'stuttering' ..

**Comment by jjd-uk** [comment]
> I think the link/file is wrong. The size is about 200k - the old MusicOSD.xml was only 13k. And: it doesn't work. Selecting a channel the screen changes to the channel, but there are no more any buttons at all.

How are you saving it? for me opening it in Chrome then right clicking and selecting Save As gives a 16k file.

**Comment by gade01** [comment]
Copy/paste this code into your existing MusicOSD.xml

Replace everything.

```<?xml version="1.0" encoding="UTF-8"?>
<window>
	<defaultcontrol always="true">100</defaultcontrol>
	<onload condition="!MusicPlayer.Content(LiveTV)">SetFocus(602)</onload>
	<include>dialogeffect</include>
	<depth>DepthOSD</depth>
	<coordinates>
		<left>0</left>
		<top>0</top>
	</coordinates>
	<controls>
		<control type="button">
			<description>Close Window button</description>
			<left>84r</left>
			<top>0</top>
			<width>64</width>
			<height>32</height>
			<label/>
			<font/>
			<onclick>Dialog.Close(MusicOSD,true)</onclick>
			<onclick>FullScreen</onclick>
			<texturefocus>DialogCloseButton-focus.png</texturefocus>
			<texturenofocus>DialogCloseButton.png</texturenofocus>
			<animation effect="fade" time="150">VisibleChange</animation>
			<animation effect="slide" start="0,0" end="-30,0" time="0" condition="Player.Muted">conditional</animation>
			<visible>system.getbool(input.enablemouse) + ![Window.IsVisible(AddonSettings) | Window.IsVisible(SelectDialog) | Window.IsVisible(VisualisationPresetList) | Window.IsVisible(PVROSDChannels) | Window.IsVisible(PVRChannelGuide) | Window.IsVisible(PVRRadioRDSInfo) | Window.IsVisible(Addon)]</visible>
		</control>
		<control type="slider" id="87">
			<depth>DepthOSD+</depth>
			<description>Seek Slider</description>
			<left>430</left>
			<top>82r</top>
			<width>720</width>
			<height>16</height>
			<onup>702</onup>
			<ondown>26</ondown>
			<action>seek</action>
			<texturesliderbar>seekslider2.png</texturesliderbar>
			<textureslidernib>osd_slider_nibNF.png</textureslidernib>
			<textureslidernibfocus>osd_slider_nib.png</textureslidernibfocus>
			<animation effect="fade" time="150">VisibleChange</animation>
			<visible>![Window.IsVisible(AddonSettings) | Window.IsVisible(SelectDialog) | Window.IsVisible(VisualisationPresetList) | Window.IsVisible(PVROSDChannels) | Window.IsVisible(PVRChannelGuide) | Window.IsVisible(PVRRadioRDSInfo) | Window.IsVisible(Addon)]</visible>
		</control>
		<control type="grouplist" id="100">
			<left>325</left>
			<top>60r</top>
			<orientation>horizontal</orientation>
			<itemgap>0</itemgap>
			<animation effect="fade" time="150">VisibleChange</animation>
			<visible>![Window.IsVisible(AddonSettings) | Window.IsVisible(SelectDialog) | Window.IsVisible(VisualisationPresetList) | Window.IsVisible(PVROSDChannels) | Window.IsVisible(PVRChannelGuide) | Window.IsVisible(PVRRadioRDSInfo) | Window.IsVisible(Addon)]</visible>
			<control type="button" id="300">
				<width>55</width>
				<height>55</height>
				<label>210</label>
				<font/>
				<texturefocus>OSDChannelUPFO.png</texturefocus>
				<texturenofocus>OSDChannelUPNF.png</texturenofocus>
				<onclick>PlayerControl(Previous)</onclick>
				<visible>MusicPlayer.Content(LiveTV)</visible>
			</control>
			<control type="button" id="301">
				<width>55</width>
				<height>55</height>
				<label>209</label>
				<font/>
				<texturefocus>OSDChannelDownFO.png</texturefocus>
				<texturenofocus>OSDChannelDownNF.png</texturenofocus>
				<onclick>PlayerControl(Next)</onclick>
				<visible>MusicPlayer.Content(LiveTV)</visible>
			</control>
			<control type="button" id="600">
				<width>55</width>
				<height>55</height>
				<label>210</label>
				<font/>
				<texturefocus>OSDPrevTrackFO.png</texturefocus>
				<texturenofocus>OSDPrevTrackNF.png</texturenofocus>
				<onclick>PlayerControl(Previous)</onclick>
				<visible>!MusicPlayer.Content(LiveTV)</visible>
			</control>
			<control type="button" id="601">
				<width>55</width>
				<height>55</height>
				<label>31354</label>
				<font/>
				<texturefocus>OSDRewindFO.png</texturefocus>
				<texturenofocus>OSDRewindNF.png</texturenofocus>
				<animation effect="fade" start="100" end="50" time="75" condition="!Player.SeekEnabled">Conditional</animation>
				<onclick>PlayerControl(Rewind)</onclick>
				<enable>Player.SeekEnabled</enable>
			</control>
			<control type="togglebutton" id="602">
				<width>55</width>
				<height>55</height>
				<label>31351</label>
				<altlabel>208</altlabel>
				<font/>
				<texturefocus>OSDPauseFO.png</texturefocus>
				<texturenofocus>OSDPauseNF.png</texturenofocus>
				<usealttexture>Player.Paused | Player.Forwarding | Player.Rewinding</usealttexture>
				<alttexturefocus>OSDPlayFO.png</alttexturefocus>
				<alttexturenofocus>OSDPlayNF.png</alttexturenofocus>
				<animation effect="fade" start="100" end="50" time="75" condition="!Player.PauseEnabled">Conditional</animation>
				<onclick>PlayerControl(Play)</onclick>
				<enable>Player.PauseEnabled</enable>
			</control>
			<control type="button" id="603">
				<width>55</width>
				<height>55</height>
				<label>31352</label>
				<font/>
				<texturefocus>OSDStopFO.png</texturefocus>
				<texturenofocus>OSDStopNF.png</texturenofocus>
				<onclick>PlayerControl(Stop)</onclick>
			</control>
			<control type="button" id="604">
				<width>55</width>
				<height>55</height>
				<label>31353</label>
				<font/>
				<texturefocus>OSDForwardFO.png</texturefocus>
				<texturenofocus>OSDForwardNF.png</texturenofocus>
				<animation effect="fade" start="100" end="50" time="75" condition="!Player.SeekEnabled">Conditional</animation>
				<onclick>PlayerControl(Forward)</onclick>
				<enable>Player.SeekEnabled</enable>
			</control>
			<control type="button" id="605">
				<width>55</width>
				<height>55</height>
				<label>209</label>
				<font/>
				<texturefocus>OSDNextTrackFO.png</texturefocus>
				<texturenofocus>OSDNextTrackNF.png</texturenofocus>
				<visible>!MusicPlayer.Content(LiveTV)</visible>
				<onclick>PlayerControl(Next)</onclick>
			</control>
			<control type="button" id="306">
				<width>55</width>
				<height>55</height>
				<label>19019</label>
				<font/>
				<texturefocus>OSDChannelListFO.png</texturefocus>
				<texturenofocus>OSDChannelListNF.png</texturenofocus>
				<onclick>ActivateWindow(PVROSDChannels)</onclick>
				<visible>MusicPlayer.Content(LiveTV)</visible>
			</control>
			<control type="button" id="307">
				<width>55</width>
				<height>55</height>
				<label>$LOCALIZE[19029]$INFO[MusicPlayer.ChannelName, - ]</label>
				<font/>
				<texturefocus>OSDepgFO.png</texturefocus>
				<texturenofocus>OSDepgNF.png</texturenofocus>
				<onclick>ActivateWindow(PVRChannelGuide)</onclick>
				<visible>MusicPlayer.Content(LiveTV) + !RDS.HasRadiotextPlus</visible>
			</control>
			<control type="button" id="308">
				<visible>RDS.HasRadiotextPlus</visible>
				<width>55</width>
				<height>55</height>
				<label>209</label>
				<font/>
				<texturefocus>OSDRadioRDSFO.png</texturefocus>
				<texturenofocus>OSDRadioRDSNF.png</texturenofocus>
				<onclick>ActivateWindow(PVRRadioRDSInfo)</onclick>
				<visible>MusicPlayer.Content(LiveTV) + RDS.HasRadiotextPlus</visible>
			</control>
			<control type="group" id="699">
				<width>55</width>
				<height>55</height>
				<visible>!MusicPlayer.Content(LiveTV)</visible>
				<control type="button" id="606">
					<left>0</left>
					<top>0</top>
					<width>55</width>
					<height>55</height>
					<label>$LOCALIZE[486]$INFO[Playlist.Repeat, : ]</label>
					<font/>
					<texturefocus/>
					<texturenofocus/>
					<onleft>605</onleft>
					<onright>607</onright>
					<onclick>PlayerControl(Repeat)</onclick>
				</control>
				<control type="image">
					<left>0</left>
					<top>0</top>
					<width>55</width>
					<height>55</height>
					<texture>OSDRepeatNF.png</texture>
					<visible>!Playlist.IsRepeat + !Playlist.IsRepeatOne</visible>
					<visible>!Control.HasFocus(606)</visible>
				</control>
				<control type="image">
					<left>0</left>
					<top>0</top>
					<width>55</width>
					<height>55</height>
					<texture>OSDRepeatFO.png</texture>
					<visible>!Playlist.IsRepeat + !Playlist.IsRepeatOne</visible>
					<visible>Control.HasFocus(606)</visible>
				</control>
				<control type="image">
					<left>0</left>
					<top>0</top>
					<width>55</width>
					<height>55</height>
					<texture>OSDRepeatOneNF.png</texture>
					<visible>Playlist.IsRepeatOne</visible>
					<visible>!Control.HasFocus(606)</visible>
				</control>
				<control type="image">
					<left>0</left>
					<top>0</top>
					<width>55</width>
					<height>55</height>
					<texture>OSDRepeatOneFO.png</texture>
					<visible>Playlist.IsRepeatOne</visible>
					<visible>Control.HasFocus(606)</visible>
				</control>
				<control type="image">
					<left>0</left>
					<top>0</top>
					<width>55</width>
					<height>55</height>
					<texture>OSDRepeatAllNF.png</texture>
					<visible>Playlist.IsRepeat</visible>
					<visible>!Control.HasFocus(606)</visible>
				</control>
				<control type="image">
					<left>0</left>
					<top>0</top>
					<width>55</width>
					<height>55</height>
					<texture>OSDRepeatAllFO.png</texture>
					<visible>Playlist.IsRepeat</visible>
					<visible>Control.HasFocus(606)</visible>
				</control>
			</control>
			<control type="togglebutton" id="607">
				<width>55</width>
				<height>55</height>
				<label>$LOCALIZE[590]$INFO[Playlist.Random, : ]</label>
				<font/>
				<texturefocus>OSDRandomOffFO.png</texturefocus>
				<texturenofocus>OSDRandomOffNF.png</texturenofocus>
				<usealttexture>Playlist.IsRandom</usealttexture>
				<alttexturefocus>OSDRandomOnFO.png</alttexturefocus>
				<alttexturenofocus>OSDRandomOnNF.png</alttexturenofocus>
				<visible>!MusicPlayer.Content(LiveTV)</visible>
				<onclick>PlayerControl(Random)</onclick>
			</control>
			<control type="image" id="2300">
				<width>105</width>
				<texture/>
			</control>
			<control type="image" id="2400">
				<width>55</width>
				<texture/>
			</control>
			<control type="image" id="2500">
				<width>55</width>
				<texture/>
				<visible>MusicPlayer.Content(LiveTV)</visible>
			</control>
			<control type="image" id="2600">
				<width>55</width>
				<texture/>
				<visible>!PVR.CanRecordPlayingChannel</visible>
			</control>
			<control type="button" id="705">
				<width>55</width>
				<height>55</height>
				<label>563</label>
				<font/>
				<texturefocus>OSDRateFO.png</texturefocus>
				<texturenofocus>OSDRateNF.png</texturenofocus>
				<onclick>setrating</onclick>
			</control>
			<control type="togglebutton" id="701">
				<width>55</width>
				<height>55</height>
				<label>31128</label>
				<font/>
				<texturefocus>OSDLyricsFO.png</texturefocus>
				<texturenofocus>OSDLyricsNF.png</texturenofocus>
				<alttexturefocus>OSDLyricsFO.png</alttexturefocus>
				<alttexturenofocus>OSDLyricsNF.png</alttexturenofocus>
				<onclick>Close</onclick>
				<onclick>RunScript($INFO[Skin.String(LyricScript_Path)])</onclick>
				<altclick>Skin.SetAddon(LyricScript_Path,xbmc.python.lyrics)</altclick>
				<altclick>Close</altclick>
				<altclick>RunScript($INFO[Skin.String(LyricScript_Path)])</altclick>
				<usealttexture>String.IsEmpty(Skin.String(LyricScript_Path))</usealttexture>
				<visible>!MusicPlayer.Content(LiveTV)</visible>
			</control>
			<control type="button" id="500">
				<width>55</width>
				<height>55</height>
				<label>12006</label>
				<font/>
				<texturefocus>OSDVizFO.png</texturefocus>
				<texturenofocus>OSDVizNF.png</texturenofocus>
			</control>
			<control type="button" id="702">
				<width>55</width>
				<height>55</height>
				<label>$LOCALIZE[250] $LOCALIZE[21417]</label>
				<font/>
				<texturefocus>OSDPresetSettingsFO.png</texturefocus>
				<texturenofocus>OSDPresetSettingsNF.png</texturenofocus>
				<onclick>Addon.Default.OpenSettings(xbmc.player.musicviz)</onclick>
			</control>
			<control type="button" id="703">
				<width>55</width>
				<height>55</height>
				<label>31048</label>
				<font/>
				<texturefocus>OSDPreFO.png</texturefocus>
				<texturenofocus>OSDPreNF.png</texturenofocus>
				<onclick>ActivateWindow(visualisationpresetlist)</onclick>
				<enable>Visualisation.HasPresets</enable>
				<animation effect="fade" start="100" end="50" time="75" condition="!Visualisation.HasPresets">Conditional</animation>
			</control>
			<control type="togglebutton" id="704">
				<width>55</width>
				<height>55</height>
				<label>264</label>
				<altlabel>265</altlabel>
				<font/>
				<texturefocus>OSDRecordOffFO.png</texturefocus>
				<texturenofocus>OSDRecordOffNF.png</texturenofocus>
				<usealttexture>PVR.IsRecordingPlayingChannel | PVR.IsPlayingActiveRecording</usealttexture>
				<alttexturefocus>OSDRecordOnFO.png</alttexturefocus>
				<alttexturenofocus>OSDRecordOnNF.png</alttexturenofocus>
				<onclick>PVR.ToggleRecordPlayingChannel</onclick>
				<visible>PVR.CanRecordPlayingChannel</visible>
			</control>
		</control>
	</controls>
</window>```

**Comment by Max11223344** [comment]
This is the file i downloaded (only the first lines of total 2446)

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
  <link rel="dns-prefetch" href="https://avatars.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">



  <link crossorigin="anonymous" media="all" integrity="sha512-rF3cnLJE5IkKUWFkw54emxUMV82DhbZ9aJun83zhvBgJ7J7ZXC20bEFVuLY9RRRC60Ig+pHQO57DuYBrYO+cAA==" rel="stylesheet" href="https://github.githubassets.com/assets/frameworks-ac5ddc9cb244e4890a516164c39e1e9b.css" />
  <link crossorigin="anonymous" media="all" integrity="sha512-J4RxNaraZOBAqhiAjrEgwD8axqRMCxhDluOkWMHlruCmKfJ3vW9ZnXLL0VuuxIB3UeohN7OBmlrm6nUhBrynPw==" rel="stylesheet" href="https://github.githubassets.com/assets/site-27847135aada64e040aa18808eb120c0.css" />
    <link crossorigin="anonymous" media="all" integrity="sha512-1EljEQGYZdLAetENjUOq/rHuLetaeyG7zCtvdUsmgcLBDZBzrrDlhlBkBDKz3lfyEvuHlvmbYjX0RxQ9prAVGA==" rel="stylesheet" href="https://github.githubassets.com/assets/behaviors-d4496311019865d2c07ad10d8d43aafe.css" />

**Comment by Max11223344** [comment]
<!DOCTYPE html>
     <html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
  <link rel="dns-prefetch" href="https://avatars.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">



  <link crossorigin="anonymous" media="all" integrity="sha512-rF3cnLJE5IkKUWFkw54emxUMV82DhbZ9aJun83zhvBgJ7J7ZXC20bEFVuLY9RRRC60Ig+pHQO57DuYBrYO+cAA==" rel="stylesheet" href="https://github.githubassets.com/assets/frameworks-ac5ddc9cb244e4890a516164c39e1e9b.css" />
  <link crossorigin="anonymous" media="all" integrity="sha512-J4RxNaraZOBAqhiAjrEgwD8axqRMCxhDluOkWMHlruCmKfJ3vW9ZnXLL0VuuxIB3UeohN7OBmlrm6nUhBrynPw==" rel="stylesheet" href="https://github.githubassets.com/assets/site-27847135aada64e040aa18808eb120c0.css" />
    <link crossorigin="anonymous" media="all" integrity="sha512-1EljEQGYZdLAetENjUOq/rHuLetaeyG7zCtvdUsmgcLBDZBzrrDlhlBkBDKz3lfyEvuHlvmbYjX0RxQ9prAVGA==" rel="stylesheet" href="https://github.githubassets.com/assets/behaviors-d4496311019865d2c07ad10d8d43aafe.css" />

**Comment by Max11223344** [comment]
<!DOCTYPE html>
 <html lang="en">
   <head>
     <meta charset="utf-8">
   <link rel="dns-prefetch" href="https://github.githubassets.com">
   <link rel="dns-prefetch" href="https://avatars.githubusercontent.com">
   <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
   <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">



  <link crossorigin="anonymous" media="all" integrity="sha512-rF3cnLJE5IkKUWFkw54emxUMV82DhbZ9aJun83zhvBgJ7J7ZXC20bEFVuLY9RRRC60Ig+pHQO57DuYBrYO+cAA==" rel="stylesheet" href="https://github.githubassets.com/assets/frameworks-ac5ddc9cb244e4890a516164c39e1e9b.css" />
  <link crossorigin="anonymous" media="all" integrity="sha512-J4RxNaraZOBAqhiAjrEgwD8axqRMCxhDluOkWMHlruCmKfJ3vW9ZnXLL0VuuxIB3UeohN7OBmlrm6nUhBrynPw==" rel="stylesheet" href="https://github.githubassets.com/assets/site-27847135aada64e040aa18808eb120c0.css" />
    <link crossorigin="anonymous" media="all" integrity="sha512-1EljEQGYZdLAetENjUOq/rHuLetaeyG7zCtvdUsmgcLBDZBzrrDlhlBkBDKz3lfyEvuHlvmbYjX0RxQ9prAVGA==" rel="stylesheet" href="https://github.githubassets.com/assets/behaviors-d4496311019865d2c07ad10d8d43aafe.css" />

**Comment by gade01** [comment]
I think you downloaded the file as html (which will probably break everything) instead of xml.

Read my previous post and copy/paste instead.

**Comment by Max11223344** [comment]
why cant i copy some records from that file?
i think i will forget my wish for the red button. For me the case is closed.
Sorry

**Comment by gade01** [comment]
FFS.

I wrote above how you can copy/paste into your  existing MusicOSD.xml file.

I spend time last night trying to fix your issue.
Try at least to show some appreciation.

**Comment by Max11223344** [comment]
I appreciate your work. FFS doesn't help. And i am not stupid. The target of the link was changed. The first time i downloaded it it was 2448 lines, starting with Doctype html. Now the link brings another file with about 300 lines. I know how to a) download b) copy. Sorry, don't fool me
[MusicOSD1.xml.txt](https://github.com/xbmc/skin.confluence/files/5995513/MusicOSD1.xml.txt)

**Comment by Max11223344** [comment]
Ok. It seems to work now. Thank you

**Comment by gade01** [comment]
Great, thanks a lot for testing it.
Glad we got it working.

**Pull request merged**
