### PR TITLE
[chg] add-ons/settings: adjust for xbmc/pull/12125

### PR DESCRIPTION
**Pull request by stefansaraev**
a poor attempt to make addon settings work after https://github.com/xbmc/xbmc/pull/12125

this needs testing, I am really bad at skinning and not sure I am doing the positioning right

DialogAddonSettings.xml is now basicaly same as DialogSettings.xml with some small changes:

- control id 9001 is re-positioned to fit the new "defaults" button.
- added conrtols for categories area on top.

here is the diff http://sprunge.us/PgVa

### CODE REVIEW

**Comment by stefansaraev** [comment]
updated. minor cosmetics.

**Comment by HitcherUK** [comment]
Thanks.

**Comment by HitcherUK** [comment]
@stefansaraev global search doesn't show the 'General' category button label anymore

screenshot000

**Comment by stefansaraev** [comment]
uhm. not sure where string with id 30100 for that category label comes from. does it work in estuary?

**Comment by stefansaraev** [comment]
https://github.com/ronie/script.globalsearch/blob/master/resources/language/English/strings.po#L19-L21

https://github.com/ronie/script.globalsearch/blob/master/resources/settings.xml#L3 <- here, should be 30200

**Comment by HitcherUK** [comment]
Thanks, I'll let ronie now.

**Pull request merged**
