### PR TITLE
Omega version

### PR DESCRIPTION
**Pull request by Hitcher**
Omega updates including conversion from 720p to 1080p.

- Add video version/extra select dialog
- Fix panel height
- Fix Original/Localised title
- Fix 'Movie' and 'TV Shows' buttons visible condition
- Fix addon focus issue
- Fix Formed/Born overlap issue
- Fix exiting from settings focus problem
- Fix missing label in view id=50
- Fix broken bool in PosterThumb variable
- Fix default home item selection issue
- Remove unneeded code
- Fix default select item when using login
- Remove unneeded close button
- Rework versions/extras textures
- Add Video version support
- Convert skin from 720p to 1080p
- Update scrollbars
- Add grid overlay
- Add game agents
- Add disabled slider texture

### CODE REVIEW

**Comment by Hitcher** [comment]
Any help with the conflict appreciated.

**Comment by bkuhls** [comment]
> Omega updates including conversion from 720p to 1080p.

Never used an Arial-based font before so I can not tell if it looked small before but now with 1080p it is imho too small. Am I missing something or should I try to increase the size values in 1080p/Font.xml?

**Comment by Hitcher** [comment]
> Never used an Arial-based font before so I can not tell if it looked small before but now with 1080p it is imho too small. Am I missing something or should I try to increase the size values in 1080p/Font.xml?

The Font.xml has been converted.

**Comment by Hitcher** [comment]
Conflict sorted.

**Comment by bossanova808** [comment]
Noticed another little bug.   If you play a movie via the recently added icons on the home page then stop it, the focus goes off...I get add-ons focused. Same with playing an album from the home page and stopping it, then I ended up with system focused. 

Minor, but a bit weird!

**Comment by DaVukovic** [comment]
I can confirm. I got "system" focused after playing a movie from that section

**Comment by Hitcher** [comment]
> Noticed another little bug. If you play a movie via the recently added icons on the home page then stop it, the focus goes off...I get add-ons focused. Same with playing an album from the home page and stopping it, then I ended up with system focused.

Fixed, thanks.

**Pull request merged**
