### PR TITLE
[skin.confluence] Restore view mode/sizing info

### PR DESCRIPTION
**Pull request by glenvt18**
It was accidentally deleted by a57f776.

### CODE REVIEW

**Comment by stefansaraev** [comment]
ups. indeed. I overlooked it. sorry for that ;(

**Comment by stefansaraev** [comment]
@glenvt18 you can rebase on master and pick https://github.com/stefansaraev/skin.tb/commit/faa136000af6de220cf60b7931ad1fa627bcb7b3

cc @HitcherUK

**Comment by HitcherUK** [comment]
This info is now redundant and has been replaced with DialogPlayerProcessInfo.xml

**Comment by stefansaraev** [comment]
> This info is now redundant and has been replaced with DialogPlayerProcessInfo.xml

that's correct, but it's still good to have the info immediately available on screen when user is switching between view modes (normal, wide zoom, stretch 16x9 etc) - the so called AspectRatio action mapped by default to keyboard z. up to you

**Comment by HitcherUK** [comment]
Sorry, didn't realise it was used to show that info as well. Thanks.

**Pull request merged**
